name: Docker push container at org level (GITHUB_TOKEN)
on: push

permissions:
 packages: write

jobs:
 all:
  runs-on: ubuntu-latest
  
  steps:
   - name: Login to GitHub container Registry
     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
   - name: Build the Docker image
     run: docker pull glassfish:latest
   - name: tag the Docker image
     run: docker tag glassfish:latest ghcr.io/aashijtestorg/glassfish:latest
   - name: Push the Docker image to the registry
     run: docker push ghcr.io/aashijtestorg/glassfish:latest
